var GAME_LEVELS = [
  ["                                                                            xx  ",
   "  xx                                      o o                                x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxxx                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @       x  x                                                xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx!!!xxxxxxxxxxxxxxxxxxxx!!!!!xxxxxxx   xxxxxxxxx  "],
  ["                                               x           ",
   "                                               x           ",
   "                                               x           ",
   "                                               x           ",
   "                                               xx    x     ",
   "                                               x     x     ",
   "               xxxxxxx        xxx   xxx        x     x     ",
   "              xx     xx         x   x          x     x     ",
   "             xx       xx        x o x          x    xx  o  ",
   "     @       x         x        x   x          x     x  o  ",
   "    xxx      x         x        x   x          x     x     ",
   "    x x      x         x       xx o xx         x     x     ",
   "!!!!x x!!!!!!x         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxx     x!!!!!",
   "!!!!x x!!!!!!x         x!!!!!x    o                 xx!!!!!",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!x",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx"],
  ["  xxx                         x                                          x",
   "  x x                         x                                          x",
   "  x                           x         xxxxxxxxx                        x",
   "  x                           x           x                              x",
   "  x                           xxx         x                              x",
   "  x                                     xxx       |xxxx|    |xxxx|     xxx",
   "  x                xxx             o o    x                              x",
   "  x               xxxxx       xx          x                             xx",
   "  x               oxxxo       x    xxx    x                             x ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   "],
  ["  xxxxxxxxxxx                                 x",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx    x",
   "  x         x   x       x   x       x   x     x",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx     x",
   "  xxxxxxx                                     x",
   "        x=                  =                =x",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
  ["xxxxxx x     x xxxxx  ",
   "x      xx    x x    x ",
   "x      x x   x x     x",
   "xxxxxx x  x  x x     x",
   "x      x   x x x     x",
   "x      x    xx x    x ",
   "xxxxxx x     x xxxxx  "]
  
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
